language: csharp
mono: none
dotnet: 1.1.5
script:
 - dotnet restore
 - cd ReliableDbConnectionWrapper
 - dotnet build -f netstandard1.4
 - cd ../ReliableDbConnectionWrapper.Tests
 - dotnet build
 - dotnet test
